<a href="https://colab.research.google.com/github/SaimKhan9/Numpy/blob/main/Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4])

In [7]:
arr1


array([1, 2, 3, 4])

In [24]:
arr2=np.zeros(())

In [25]:
arr2

array(0.)

In [26]:
arr3=np.identity(5)

In [27]:
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr4=np.arange(5,50,5)

In [35]:
arr4

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [42]:
arr5=np.linspace(10,20,10)

In [43]:
arr5

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [44]:
arr6=arr5.copy()

In [45]:
arr6

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])