<a href="https://colab.research.google.com/github/SaimKhan9/Numpy/blob/main/Prop_Attribtes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1.shape

(5,)

In [8]:
arr2=np.array(([1,2,3],[5,6,7]))

In [9]:
arr2.shape

(2, 3)

In [10]:
arr3=np.array([[[1,2],[3,4]],[[1,0],[9,0]]])

In [11]:
arr3

array([[[1, 2],
        [3, 4]],

       [[1, 0],
        [9, 0]]])

In [12]:
arr3.shape

(2, 2, 2)

In [13]:
#to find number of dimentions
arr3.ndim

3

In [14]:
arr1.ndim

1

In [15]:
arr1.size

5

In [ ]:
#size of the array
arr2.size

6

In [ ]:
#memory of each value in array
arr2.itemsize

8

In [16]:
arr4=np.array([1,2,3])

In [17]:
arr3.itemsize

8

In [ ]:
arr3

array([[[1, 2],
        [3, 4]],

       [[1, 0],
        [9, 0]]])

In [ ]:
arr3.itemsize

8

In [18]:
arr3.dtype

dtype('int64')

In [20]:
arr1.dtype

dtype('int64')

In [22]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])